@echo off
REM Load language strings from language pack
REM This file is generated by get_batch_language.js

setlocal enabledelayedexpansion

REM Try to load language from generated file
if exist "batch_language_env.bat" (
    call batch_language_env.bat
) else (
    REM Fallback to default (English)
    set BATCH_SETUP_TITLE=Stock Accounting System - Setup
    set BATCH_START_TITLE=Stock Accounting System - Start
    set BATCH_STOP_TITLE=Stock Accounting System - Stop
    set BATCH_COMMON_ERROR=ERROR
    set BATCH_COMMON_INFO=INFO
    set BATCH_COMMON_SUCCESS=SUCCESS
    set BATCH_COMMON_WARN=WARN
)

REM Generate language file if it doesn't exist
if not exist "batch_language_env.bat" (
    if exist "get_batch_language.js" (
        node get_batch_language.js >nul 2>&1
        if exist "batch_language_env.bat" (
            call batch_language_env.bat
        )
    )
)

endlocal


